// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvGrnklH-uu9PdfM8U3VUD556K9EOFQaw',
    appId: '1:45979391503:android:02184dbdd0d8f4edf8b57a',
    messagingSenderId: '45979391503',
    projectId: 'pfeecoroute',
    databaseURL: 'https://pfeecoroute-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pfeecoroute.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM1l8uvHgIwAUE32-0YXn9yyrZDfD6Ihk',
    appId: '1:45979391503:ios:4e09f7c5f7a15da2f8b57a',
    messagingSenderId: '45979391503',
    projectId: 'pfeecoroute',
    databaseURL: 'https://pfeecoroute-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pfeecoroute.appspot.com',
    iosClientId: '45979391503-kleaj7qqr10hmr0p99k02dnp4n05blkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoRouteSe',
  );
}
